name: CI

on:
  push:
  pull_request:
    branches: [ master ]
    types: [ opened, closed ]
  workflow_dispatch:

jobs:
  backend-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy to backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd AC41004-Backend/
            git pull
            docker compose up -d --build