name: CI

on:
  push:
  pull_request:
    branches: [ master ]
    types: [ opened, closed ]
  workflow_dispatch:

jobs:
  backend-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy to backend
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd AC41004-Backend/
            git pull
            docker compose build --no-cache --progress plain
            docker compose up -d